### PR TITLE
Plot multiple point clouds with random color with python

### PR DESCRIPTION
**Pull request by OmriTreidel**
Additional plotting function in the python binding for plotting multiple point clouds

### CODE REVIEW

**Comment by c42f** [comment]
Cool, thanks for the pull request :-)  This looks undeniably useful, though I feel a bit unsure about having a new function for this very specific use case.  (The fact that you need a new function is basically my fault for not thinking through the binding API well at all.)

Maybe it would be better in the medium term to do something like in the C++ binding: make a point list class where it's easy to append points with arbitrary attributes, to be plotted all at once at the end.  The you could build a version of `multi_plot` as a trivial wrapper.  Let's see, how might the usage of such a thing look.

```python

position_list = whatever()

points = displaz.PointArray()
for i, position in enumerate(position_list):
    points.append(position, color=np.random.rand(3), cloud_index=i)
displaz.plot(points)
```

Not too bad I guess?  The attribute `cloud_index` is just there to illustrate how you could add additional attributes onto the point list (attributes which become available in the shader).

**Comment by c42f** [comment]
Sorry for sitting on this so long.  Are you still interested in having this?

I don't want to merge what you've got in quite the current state, but I have in mind something that would be harmonious with user expectations from other plotting packages:  Just make `displaz.plot()` select a new deterministic colour each time a data set is plotted.  If the user doesn't explicitly set the colour, use the autogenerated version.

**Comment by OmriTreidel** [comment]
No worries. I've made my own copy of python binding do I'm using it :) I
agree that it's not the best way to do it, it was the only way I could
think off.

**Comment by c42f** [comment]
In the interests of cleaning up, I'm going to close this since I don't want to merge it as-is.  Feel free to open a new one though.

**Comment by OmriTreidel** [comment]
OK, cheers

**Pull request closed without merging**
