### PR TITLE
Fix appveyor build for Windows packaging

### PR DESCRIPTION
**Pull request by evetion**
Removed extra platform folder in packaging
Set path to include Qt, so packaging can find Qt dlls

This PR includes c42f:fix-windows-package

See my build https://ci.appveyor.com/project/evetion/displaz/build/1

### CODE REVIEW

**Comment by c42f** [comment]
I grabbed the artifact `displaz-0.3.1-396-gba56fc3+196-win64.exe` from the appveyor build (https://ci.appveyor.com/project/c42f/displaz/build/196/artifacts) but it seems that some packaging problems are still present.  Installing it and attempting to run gives an error

"The procedure entry point ?toLower@QString@@QEGBA?AV1@XZ could not be located in the dynamic link library Qt5Core.dll"

The test machine is a windows 7 VM.  Any thoughts?

**Comment by evetion** [comment]
Latest commit seems to have fixed it:
https://ci.appveyor.com/project/c42f/displaz/build/artifacts

**Comment by c42f** [comment]
Ah ha!  Very much appreciated, thanks :-)

**Comment by c42f** [comment]
I rebased before merging to keep the history a bit neater.  Now github is confused, but I think it should all be there.  (The latest build is still failing, but that's due to a deploy issue on master - I just pushed something that should fix it, I hope.)

**Pull request closed without merging**
