### PR TITLE
Remote command -notify for scripting access to log window

### PR DESCRIPTION
**Pull request by c42f**
Implement only log:<level> for the logspec, for now.  Potentially more
in the future.  @andyferris how does this look for #136 ?

### CODE REVIEW

**Comment by andyferris** [comment]
Beautiful. :) Thanks Chris

**Comment by c42f** [comment]
Cool, I'll merge this then, and we can see how it goes.

**Comment by c42f** [comment]
Huh, hold on, travis is failing.

**Comment by c42f** [comment]
Yikes, that's quite a bug at main.cpp:129 caught by travis.  I have *no* idea why this worked locally in testing, it should have segfaulted nicely, or something.

**Comment by c42f** [comment]
Well, the reason that worked at all was super obscure:

https://gcc.gnu.org/onlinedocs/gcc/Conditionally-supported-behavior.html
http://stackoverflow.com/questions/10083844/passing-non-pod-type-to-variadic-function-is-undefined-behavior

So gcc now allows classes to be passed to C-style variadic functions, and silently converts them to references which happened by ABI chance to be compatible with pointers on the other side (I guess).  Ugh.

**Comment by andyferris** [comment]
Right. Fascinating!

**Comment by c42f** [comment]
Ah, seems the OSX build failures were due to Travis OSX woes - https://www.traviscistatus.com/

**Pull request merged**
