### PR TITLE
Animated view transforms R and T (Revisited)

### PR DESCRIPTION
**Pull request by nigels-com**
Couldn't resist tinkering with https://github.com/c42f/displaz/pull/54

Rebased onto master branch and modestly refactored to be frame-rate independent.

### CODE REVIEW

**Comment by nigels-com** [comment]
Seems to me we don't need two separate timers.  This change re-purposes the existing one to trigger redraws, and moves the animation logic into paintGL.  The idea is for paintGL be called continuously for the duration of the animation.

**Comment by nigels-com** [comment]
Withdrawing this pull request, for now.  (My branch now seems buggy)

**Comment by c42f** [comment]
Ok, no probs.  I think keeping the discussion in one place on #54 makes sense anyway.  @gphysics has your first commit on his branch now.

**Comment by nigels-com** [comment]
Sure thiing.

**Pull request closed without merging**
