### PR TITLE
Migrate from OpenEXR/ilmbase to Academy Software Foundation (ASWF) Imath

### PR DESCRIPTION
**Pull request by nigels-com**
From:
https://github.com/AcademySoftwareFoundation/Imath

### CODE REVIEW

**Comment by c42f** [comment]
Makes sense :+1: Any idea what's up with CI? (btw there's no Linux CI anymore due to the death of TravisCI.org but I haven't had time to upgrade it github actions)

**Comment by nigels-com** [comment]
Yeah, seems like that version of Visual Studio is picky about constexpr constructors initialising all the data.
Might be something to go pester the ASWF people about, I just wanted the ilmbase warnings to go away!

**Comment by nigels-com** [comment]
I updated the PR to use a newer Visual Studio that seems happy with Imath as-is.
Fingers crossed.

**Comment by nigels-com** [comment]
Previous build issue fix accepted upstream.
This ought to be good to go now.

**Pull request merged**
