### PR TITLE
Reorganise GUI and OpenGL rendering code into subdirectories

### PR DESCRIPTION
**Pull request by nigels-com**
Regarding https://github.com/c42f/displaz/issues/74

No functional change, just a shuffle.

### CODE REVIEW

**Comment by c42f** [comment]
Looks reasonable.  I'm not sure where View3d belongs, since it's partly a Qt widget and partly a manager for OpenGL handles (probably a sign it needs refactoring?)  I guess the general guideline is that `gui` contains pure Qt GUI code, while `render` contain mostly OpenGL API calls + a qt utility glue as required?

To save on renaming churn, can I bother you to name the new files with the name of the main class inside (including case)?  I've been slowly moving in that direction when adding new classes, but haven't done a mass rename yet.

**Comment by nigels-com** [comment]
Yes, I was aiming for "pure Qt" in GUI, versus "rendering related including some Qt stuff" in render.  I makes sense that there are places combining those worlds.  As for renaming, sure thing, will do.

**Comment by nigels-com** [comment]
Done.

**Comment by c42f** [comment]
Merged, thanks!

**Pull request closed without merging**
